spring.datasource.url=jdbc:postgresql://localhost:5432/booking
spring.datasource.username=tests
spring.datasource.password=au$k@FuSpSK#VvB$
spring.jpa.generate-ddl=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=150MB
file.upload-dir=/home/itpw/booking/media
proxy-settings.uri=https://zm2.itpw.ru:8193/
spring.jpa.hibernate.ddl-auto=update
server.port=8192
auth.jwt.issuer=child tracker backend app
auth.jwt.ttl-in-seconds=360000000
auth.jwt.secret=RgUkXp2s5v8y/B?E(H+MbPeShVmYq3t6w9z$C&F)J@NcRfTjWnZr4u7x!A%D*G-KaPdSgVkXp2s5v8y/B?E(H+MbQeThWmZq3t6w9z$C&F)J@NcRfUjXn2r5u7x!A%D*G-KaPdSgVkYp3s6v9y/B?E(H+MbQeThWmZq4t7w!z%C&F)J@NcRfUjXn2r5u8x/A?D(G-KaPdSgVkYp3s6v9y$B&E)H@McQeThWmZq4t7w!z%C*F-JaNdRgUjXn2r5u8
yandex.api-key=a659107c-8676-4600-9841-4214288b0138